In [148]:
file1 = open('input.txt', 'r')
lines = file1.read().split('\n')

octopi_grid = np.zeros((len(lines), len(lines[0])), dtype=int)
for i in range(0, len(lines)):
    octopi_grid[i,:] = list(lines[i])
total_flashes = 0

def process_flash(indexes, grid, debug):
    for i in range(0, len(indexes[0])):
        if indexes[1][i]-1 >= 0:
            grid[max(0, indexes[0][i]-1):min(grid.shape[0], indexes[0][i]+2), max(0, indexes[1][i]-1)] += 1

        grid[max(0, indexes[0][i]-1):min(grid.shape[0], indexes[0][i]+2), indexes[1][i]] += 1
        if indexes[1][i]+1 <= grid.shape[1]-1:
            grid[max(0, indexes[0][i]-1):min(grid.shape[0], indexes[0][i]+2), min(grid.shape[1]-1, indexes[1][i]+1)] += 1

        if debug == True:
            grid[indexes[0][i], indexes[1][i]] = 0
            print(grid)
    grid[indexes] = 0
    return grid
def clear_all_flashed_octopi(all_indexes, grid):
    for indexes in all_indexes:
        grid[indexes] = 0
    return grid

def process_grid_flashes(grid, debug=False):
    global total_flashes
    all_indexes = []
    flash_indexes = np.where(grid > 9)
    total_flashes += len(flash_indexes[0])
    all_indexes.append(flash_indexes);
    while len(flash_indexes[0]) > 0:
        grid = process_flash(flash_indexes, grid, debug)
        flash_indexes = np.where(grid > 9)
        total_flashes += len(flash_indexes[0])
        all_indexes.append(flash_indexes);
        grid = clear_all_flashed_octopi(all_indexes, grid)
    return grid

for i in range(0, 1000):
    octopi_grid = process_grid_flashes(octopi_grid+1)
    if np.array_equal(octopi_grid, np.zeros((len(lines), len(lines[0])), dtype=int)):
        print(i+1)
        break
print(octopi_grid, total_flashes)


519
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]] 8225
