In [282]:
import numpy as np
import colorama
import math

In [293]:
file1 = open('input.txt', 'r')
lines = file1.read().split('\n')

dots = []
folds = []
max_x = 0
max_y = 0
for line in lines:
    if(line == ""):
        continue
    if(line.startswith("fold along ")):
        fold = line.replace("fold along ", "").split("=")
        folds.append(tuple([fold[0], int(fold[1])]))
    else:
        dot = line.split(",")
        dot = tuple([int(dot[0]), int(dot[1])])
        dots.append(dot)
        if(dot[0] > max_x): 
            max_x = dot[0]
        if(dot[1] > max_y):
            max_y = dot[1]

paper = np.zeros((max_y+2, max_x+1))
for dot in dots:
    paper[dot[1],dot[0]] = 1

for fold in folds:
    print("beginning", fold, paper.shape)
    fold_line = fold[1]
    if fold[0] == "y":
        new_paper = paper[0:fold_line,:]
        old_paper = paper[fold_line+1:,:]
        old_paper_flipped = np.fliplr(np.rot90(old_paper,-2))
    if fold[0] == "x":
        new_paper = paper[:,0:fold_line]
        old_paper = paper[:,fold_line+1:]
        old_paper_flipped = np.flipud(np.rot90(old_paper,-2))
    paper = new_paper + old_paper_flipped

def color_sign(x):
    c = colorama.Fore.GREEN if x > 1 else colorama.Fore.RED
    return f'{c}{x}'
paper[np.where(paper > 0)] = 8
print(paper)

beginning ('x', 655) (895, 1311)
beginning ('y', 447) (895, 655)
beginning ('x', 327) (447, 655)
beginning ('y', 223) (447, 327)
beginning ('x', 163) (223, 327)
beginning ('y', 111) (223, 163)
beginning ('x', 81) (111, 163)
beginning ('y', 55) (111, 81)
beginning ('x', 40) (55, 81)
beginning ('y', 27) (55, 40)
beginning ('y', 13) (27, 40)
beginning ('y', 6) (13, 40)
[[8.0 8.0 8.0 8.0 0.0 0.0 8.0 8.0 0.0 0.0 8.0 0.0 0.0 8.0 0.0 8.0 0.0 0.0 8.0 0.0 8.0 8.0 8.0 0.0 0.0 8.0 8.0 8.0 8.0 0.0 0.0 8.0 8.0 0.0 0.0 8.0 8.0 8.0 0.0 0.0]
 [8.0 0.0 0.0 0.0 0.0 8.0 0.0 0.0 8.0 0.0 8.0 0.0 0.0 8.0 0.0 8.0 0.0 8.0 0.0 0.0 8.0 0.0 0.0 8.0 0.0 8.0 0.0 0.0 0.0 0.0 8.0 0.0 0.0 8.0 0.0 8.0 0.0 0.0 8.0 0.0]
 [8.0 8.0 8.0 0.0 0.0 8.0 0.0 0.0 8.0 0.0 8.0 8.0 8.0 8.0 0.0 8.0 8.0 0.0 0.0 0.0 8.0 0.0 0.0 8.0 0.0 8.0 8.0 8.0 0.0 0.0 8.0 0.0 0.0 0.0 0.0 8.0 0.0 0.0 8.0 0.0]
 [8.0 0.0 0.0 0.0 0.0 8.0 8.0 8.0 8.0 0.0 8.0 0.0 0.0 8.0 0.0 8.0 0.0 8.0 0.0 0.0 8.0 8.0 8.0 0.0 0.0 8.0 0.0 0.0 0.0 0.0 8.0 0.0 0.0 0.0 0.0 