In [173]:
file1 = open('input.txt', 'r')
lines = file1.read().split('\n')

dots = []
folds = []
max_x = 0
max_y = 0
for line in lines:
    if(line == ""):
        continue
    if(line.startswith("fold along ")):
        fold = line.replace("fold along ", "").split("=")
        folds.append(tuple([fold[0], int(fold[1])]))
    else:
        dot = line.split(",")
        dot = tuple([int(dot[0]), int(dot[1])])
        dots.append(dot)
        if(dot[0] > max_x): 
            max_x = dot[0]
        if(dot[1] > max_y):
            max_y = dot[1]

paper = np.zeros((max_y+1, max_x+1))
for dot in dots:
    paper[dot[1],dot[0]] = 1

for fold in folds:
    if fold[0] == "y":
        print("beginning", fold, paper.shape)
        new_paper = paper[0:(fold[1]-1),:]
        old_paper = paper[(fold[1]+1):,:]
        old_paper_flipped = np.fliplr(np.rot90(old_paper,-2))
    if fold[0] == "x":
        new_paper = paper[:,0:fold[1]]
        old_paper = paper[:,fold[1]+1:]

        old_paper_flipped = np.flipud(np.rot90(old_paper,-2))
    paper = new_paper + old_paper_flipped

def color_sign(x):
    c = colorama.Fore.GREEN if x > 1 else colorama.Fore.RED
    return f'{c}{x}'
paper[np.where(paper > 0)] = 8
print(paper)

beginning ('y', 447) (894, 655)
beginning ('y', 223) (446, 327)
beginning ('y', 111) (222, 163)
beginning ('y', 55) (110, 81)
beginning ('y', 27) (54, 40)
beginning ('y', 13) (26, 40)
beginning ('y', 6) (12, 40)
[[8.0 8.0 8.0 0.0 0.0 8.0 8.0 8.0 8.0 0.0 8.0 0.0 0.0 8.0 0.0 8.0 0.0 8.0 8.0 0.0 8.0 8.0 8.0 8.0 0.0 8.0 8.0 0.0 8.0 0.0 8.0 8.0 0.0 8.0 0.0 8.0 8.0 8.0 8.0 0.0]
 [8.0 8.0 0.0 0.0 0.0 8.0 0.0 0.0 8.0 0.0 8.0 8.0 8.0 8.0 0.0 8.0 8.0 0.0 0.0 0.0 8.0 0.0 0.0 8.0 0.0 8.0 8.0 8.0 0.0 0.0 8.0 0.0 0.0 8.0 0.0 8.0 0.0 0.0 8.0 0.0]
 [8.0 8.0 8.0 0.0 0.0 8.0 8.0 8.0 8.0 0.0 8.0 8.0 8.0 8.0 0.0 8.0 8.0 8.0 0.0 0.0 8.0 8.0 8.0 8.0 0.0 8.0 8.0 8.0 0.0 0.0 8.0 0.0 0.0 0.0 0.0 8.0 8.0 8.0 8.0 0.0]
 [8.0 0.0 0.0 0.0 0.0 8.0 8.0 8.0 8.0 0.0 8.0 0.0 0.0 8.0 0.0 8.0 0.0 8.0 0.0 0.0 8.0 8.0 8.0 0.0 0.0 8.0 0.0 0.0 0.0 0.0 8.0 0.0 0.0 0.0 0.0 8.0 8.0 0.0 0.0 0.0]
 [8.0 8.0 8.0 8.0 0.0 8.0 0.0 0.0 8.0 0.0 8.0 0.0 0.0 8.0 0.0 8.0 0.0 8.0 8.0 0.0 8.0 0.0 8.0 8.0 0.0 8.0 8.0 8.0 0.0 0.0 8.0 8.0 8.0 8.